default:
  image: node:lts
  before_script: 
    - npm ci --cache .npm --prefer-offline
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

stages:
  - deploy

job-deploy:
  stage: deploy
  script:
    - npm run build
    - npm run deploy