name = "dtps"
type = 'webpack'
account_id = '17174d3fc7098a664b04fb3c4c4ec65c'
zone_id = 'aac70c842ae479a9cc22331d1ecd2be6'
workers_dev = false
compatibility_date = "2022-01-24"

[site]
bucket = "./build"
entry-point = "."