name = "dtps"
main = "server/index.js"
compatibility_date = "2022-11-09"
account_id = "17174d3fc7098a664b04fb3c4c4ec65c"
workers_dev = false

[site]
bucket = "./build"

[[unsafe.bindings]]
type = "analytics_engine"
name = "EVENTS"
dataset = "dtps_events"