site_name: Project DTPS
site_url: https://dtps.js.org
site_description: PowerSchool LMS improvements project
site_author: jottocraft
repo_url: https://github.com/jottocraft/dtps/
theme:
    name: readthedocs
    highlightjs: true
