# This workflow will build and deploy new versions of DTPS

name: deploy

on:
  push:
    branches: [ main ]
        
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: |
        git config user.name github-actions
        git config user.email github-actions@jottocraft.com
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - run: npm ci
    - run: npm run deploy --if-present
