# This workflow will build and deploy new versions of DTPS

name: deploy

on:
  push:
    branches: [ master ]
        
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run deploy --if-present
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
