# This workflow will build and deploy new development versions of DTPS

name: dev

on:
  push:
    branches: [ dev ]
        
jobs:
  dev:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Configure git
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.DTPS_DEV_PRIVATE_KEY }}"
        git config user.name github-actions
        git config user.email github-actions@jottocraft.com

    - name: Run npm scripts
      run: npm ci
      run: npm run dev --if-present
